project:
  type: website
  output-dir: docs

website:
  title: "André Wattø Sjuve"
  site-url: https://andresjuve.com
  description: "Associate Professor of Finance at NHH Norwegian School of Economics"
  favicon: assets/images/favicon.svg
  page-navigation: true
  back-to-top-navigation: false
  search: false

  navbar:
    right:
      - text: Home
        aria-label: "Home"
        href: index.qmd
      - text: Research
        aria-label: "Research"
        href: research/index.qmd
      - text: Teaching
        aria-label: "Teaching"
        href: teaching/index.qmd
      - text: Practice
        aria-label: "Practice"
        href: practice/index.qmd
      - text: CV
        aria-label: "CV (PDF)"
        href: assets/Andre_W_Sjuve.pdf

  page-footer:
    center: >-
     &#169; 2026 André Wattø Sjuve

format:
  html:
    theme: assets/theme.scss
    highlight-style: github
    pagetitle: "{{< meta title >}}"
    description-meta: "Associate Professor of Finance at NHH Norwegian School of Economics"
    anchor-sections: false
    lightbox: true
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

execute:
  freeze: auto
