project:
  type: website
  output-dir: docs

website:
  title: "A.W. Sjuve"
  site-url: https://andresjuve.com
  description: "Assistant professor @NHH"
  favicon: assets/images/headshot.jpg
  page-navigation: true
  back-to-top-navigation: true

  navbar:
    tools:
    - icon: github
      href: https://github.com/AndreSjuve/
    right:
      - text: Home
        aria-label: "Home"
        href: index.qmd
      - text: Research
        aria-label: "Research"
        href: research/index.qmd
      - text: CV
        aria-label: "CV"
        href: assets/Andre_W_Sjuve.pdf

  page-footer:
    center: >-
     &#169; 2026 André Wattø Sjuve

format:
  html:
    theme:
      - cosmo
      - assets/theme.scss
    highlight-style: github
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute:
  freeze: auto
